function this = batchRepair

% this = mlraichle.T4ResolveBuilder.repairTriggeringOnConvertedNAC( ...
%     69, 52, 'iVisit', 1, 'tag', 'HYGLY08'); %#ok<*NASGU>
% this = mlraichle.T4ResolveBuilder.repairTriggeringOnConvertedNAC( ...
%     67, 61, 'iVisit', 1, 'tag', 'HYGLY23');
% this = mlraichle.T4ResolveBuilder.repairTriggeringOnConvertedNAC( ...
%     63, 55, 'iVisit', 2, 'tag', 'HYGLY23');
% this = mlraichle.T4ResolveBuilder.repairTriggeringOnConvertedNAC( ...
%     3, 57, 'iVisit', 1, 'tag', 'HYGLY28');
this = mlraichle.T4ResolveBuilder.repairTriggeringOnConvertedNAC( ...
    60, 52, 'iVisit', 2, 'tag', 'HYGLY28');


end