function gluTBar(xvector1, yvector1, E1, aYLabel, aTitle)
%CREATEFIGURE(XVECTOR1, YVECTOR1, E1)
%  XVECTOR1:  bar xvector
%  YVECTOR1:  bar yvector
%  E1:  errorbar e

%  Auto-generated by MATLAB on 02-Jul-2015 23:27:08

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'XTick',[45 65 75 95],'FontWeight','bold','FontSize',14);
%% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[35 100]);
hold(axes1,'on');

% Create bar
bar(xvector1,yvector1,'FaceColor',[0.7 0.7 0.7],'BarWidth',0.618);

% Create errorbar
errorbar(xvector1,yvector1,E1,'Marker','.','LineStyle','none','LineWidth',2,'Color',[0 0 0]);

% Create xlabel
xlabel('clamped plasma glu (mg/dL)');

% Create ylabel
ylabel(aYLabel);

% Create title
title(aTitle);

