HarvardOxfordCort = NIfTI.load('HarvardOxford-cort-maxprob-thr25-2mm')
HarvardOxfordSub = NIfTI.load('HarvardOxford-sub-maxprob-thr25-2mm')
HarvardOxfordCort.showimg
HarvardOxfordSub.showimg
avg152white = NIfTI.load('avg152T1_white.hdr')
avg152grey = NIfTI.load('avg152T1_grey.hdr')
avg152gray = NIfTI.load('avg152T1_gray.hdr')
avg152csf = NIfTI.load('avg152T1_csf.hdr')
mni_edges = NIfTI.load('MNI152_T1_2mm_edges')
mni_b0 = NIfTI.load('MNI152_T1_2mm_b0')
mni_brain_mask = NIfTI.load('MNI152_T1_2mm_brain_mask')
mni_strucseg_periph = NIfTI.load('MNI152_T1_2mm_strucseg_periph')
mni_2mm = NIfTI.load('MNI152_T1_2mm')
mni_2mm.showimg
L_white = (HarvardOxfortSub == 2)
L_white = (HarvardOxfordSub == 2)
L_white.showimg
L_cortex = (HarvardOxfordSub == 3)
L_thalamus = (HarvardOxfordSub == 10)
L_caudate = (HarvardOxfordSub == 11)
L_putamen = (HarvardOxfordSub == 12)
L_pallidum = (HarvardOxfordSub == 13)
brainstem = (HarvardOxfordSub == 16)
L_hippo = (HarvardOxfordSub == 17)
L_amygdala = (HarvardOxfordSub == 18)
L_accumbens = (HarvardOxfordSub == 26)
R_white = (HarvardOxfordSub == 41)
R_cortex = (HarvardOxfordSub == 42)
img: [91x109x91 double]
R_thalamus = (HarvardOxfordSub == 49)
R_caudate = (HarvardOxfordSub == 50)
R_putamen = (HarvardOxfordSub == 51)
R_pallidum = (HarvardOxfordSub == 52)
R_hippo = (HarvardOxfordSub == 53)
R_amygdala = (HarvardOxfordSub == 54)
R_accumbens = (HarvardOxfordSub == 58)
R_accumbens.showimg
t1_grey = NIfTI.load('t1_gm_stdspace')
t1_white = NIfTI.load('t1_wm_stdspace')
t1_csf = NIfTI.load('t1_csf_stdspace')
t1_first = NIfTI.load('t1_first_all_fast_firstseg')
t1_pve_csf = NIfTI.load('t1_pve_0.nii.gz')
t1_pve_white = NIfTI.load('t1_pve_1.nii.gz')
t1_pve_grey = NIfTI.load('t1_pve_2.nii.gz')
t1_pve_csf2 = NIfTI.load('t1_pve_3.nii.gz')
t1_seg_csf2 = NIfTI.load('t1_seg_3.nii.gz')
t1_seg_csf = NIfTI.load('t1_seg_0.nii.gz')
t1_seg_white = NIfTI.load('t1_seg_1.nii.gz')
t1_seg_grey = NIfTI.load('t1_seg_2.nii.gz')
tmp = avg152gray .* t1_pve_grey
t1_csf = NIfTI.load('t1_csf_stdspace_on_mni_2mm')
t1_first = NIfTI.load('t1_first_on_mni_2mm')
t1_grey = NIfTI.load('t1_gm_stdspace_on_mni_2mm')
t1_white = NIfTI.load('t1_wm_stdspace_on_mni_2mm')
t1_pve_csf = NIfTI.load('t1_pve_0_on_mni_2mm.nii.gz')
t1_pve_csf = NIfTI.load('t1_pve_csf_on_mni_2mm.nii.gz')
t1_pve_csf2 = NIfTI.load('t1_pve_csf2_on_mni_2mm.nii.gz')
t1_pve_grey = NIfTI.load('t1_pve_grey_on_mni_2mm.nii.gz')
t1_pve_white = NIfTI.load('t1_pve_white_on_mni_2mm.nii.gz')
