function txt = jsonrecode(dataOri, dataNew, varargin)
%% JSONRECODE adds additional information to existing json data objects.
%  Args:
%      dataOri (required file|text|struct): original json data in file, text or struct.
%      dataNew (required file|text|struct): new json data in file, text or struct.
%      PrettyPrint (logical): default is true.  See also web(fullfile(docroot, 'matlab/ref/jsonencode.html#namevaluepairarguments')).
%      filenameNew (text): new json filename to write.  By default writes nothing. 
%      noclobber (logical): default is false.
%  Returns:
%      txt: generated by jsonencode.
%
%  Created 02-Jan-2022 17:06:59 by jjlee in repository
%  /Users/jjlee/MATLAB-Drive/mfiles.
%  Developed on Matlab 9.11.0.1809720 (R2021b) Update 1 for MACI64.  Copyright 2022 John J. Lee.

ip = inputParser;
addRequired(ip, 'dataOri', @(x) isstruct(x) || isfile(x) || istext(x))
addRequired(ip, 'dataNew', @(x) isstruct(x) || isfile(x) || istext(x))
addParameter(ip, 'PrettyPrint', true, @islogical)
addParameter(ip, 'filenameNew', '', @istext)
addParameter(ip, 'noclobber', false, @islogical)
parse(ip, dataOri, dataNew, varargin{:});
ipr = ip.Results;

if istext(dataOri)
    if isfile(dataOri) && endsWith(dataOri, '.json', 'IgnoreCase', true)
        dataOri = fileread(dataOri);
    end
    dataOri = jsondecode(dataOri);
end
assert(isstruct(dataOri))

if istext(dataNew) 
    if isfile(dataNew) && endsWith(dataNew, '.json', 'IgnoreCase', true)
        dataNew = fileread(dataNew);
    end
    dataNew = jsondecode(dataNew);
end
assert(isstruct(dataNew))

% manage duplicates
duplicates = intersect(fields(dataOri), fields(dataNew));
if ~isempty(duplicates)
    for dupl = asrow(duplicates)
        field1 = dupl{1};
        while any(strcmp(field1, duplicates)) % search for unique field1
            field1 = strcat(field1, '_');
        end
        dataNew.(field1) = dataNew.(dupl{1});
        dataNew = rmfield(dataNew, dupl{1});
    end
end

% merge & format text
data = mergeStruct(dataOri, dataNew);
txt = jsonencode(data, 'PrettyPrint', ipr.PrettyPrint);
txt = strrep(txt, "%", "_"); % interferes with fprintf()

% write to filename
if ~isempty(ipr.filenameNew) 
    if isfile(ipr.filenameNew) && ipr.noclobber
        return
    end
    [pth,fp,x] = myfileparts(ipr.filenameNew);
    if ~strcmp(x, '.json')
        ipr.filenameNew = fulfile(pth, strcat(fp, '.json'));
    end
    fid = fopen(ipr.filenameNew, 'w');
    fprintf(fid, txt);
    fclose(fid);
end


% Created with NEWFCN.m by Frank Gonzalez-Morphy (frank.gonzalez-morphy@mathworks.de) 
% ===== EOF ====== [/Users/jjlee/MATLAB-Drive/mfiles/jsonrecode.m] ======  
