function txt = jsonrecode(dataOri, dataNew, varargin)
%% JSONRECODE adds additional information to existing json data objects.
%  Args:
%      dataOri (file|text): original json data in file, text or struct.
%      dataNew (file|text|struct) : new json data in file, text or struct.
%      Name (text): params ConvertInfAndNan | PrettyPrint.  
%                   See also web(fullfile(docroot, 'matlab/ref/jsonencode.html#namevaluepairarguments')).
%  Returns:
%      txt: generated by jsonencode.
%
%  Created 02-Jan-2022 17:06:59 by jjlee in repository
%  /Users/jjlee/MATLAB-Drive/mfiles.
%  Developed on Matlab 9.11.0.1809720 (R2021b) Update 1 for MACI64.  Copyright 2022 John J. Lee.

if istext(dataOri)
    if isfile(dataOri) && endsWith(dataOri, '.json', 'IgnoreCase', true)
        dataOri = fileread(dataOri);
    end
    dataOri = jsondecode(dataOri);
end
assert(isstruct(dataOri))
if istext(dataNew) 
    if isfile(dataNew) && endsWith(dataNew, '.json', 'IgnoreCase', true)
        dataNew = fileread(dataNew);
    end
    dataNew = jsondecode(dataNew);
end
assert(isstruct(dataNew))

data = mergeStruct(dataOri, dataNew);
txt = jsonencode(data, varargin{:});
txt = strrep(txt, "%", ""); % interferes with fprintf()


% Created with NEWFCN.m by Frank Gonzalez-Morphy (frank.gonzalez-morphy@mathworks.de) 
% ===== EOF ====== [/Users/jjlee/MATLAB-Drive/mfiles/jsonrecode.m] ======  
