%NILIO_CHECKTYPE validates that the passed type-string is recongized by the
%                nilio suite of Matlab I/O functions
%
%   USAGE:  truthValue = nilio_checkType(type)
%
%           truthValue -> 1 for true, 0 for false
%           type       -> 'uint', 'int32', 'single', 'double', 'dcomplex' etc...
%           throws error
%__________________________________________________________________________

function truthValue = nilio_checkType(type)

if (~strcmp('bin',      type) & ... 
    ~strcmp('bin8',     type) & ...
    ~strcmp('bin16',    type) & ...
    ~strcmp('bin32',    type) & ...
    ~strcmp('uint8',    type) & ...      
    ~strcmp('uint16',   type) & ...      
    ~strcmp('uint32',   type) & ...      
    ~strcmp('uint',     type) & ...      
    ~strcmp('sint8',    type) & ...      
    ~strcmp('int8',     type) & ...      
    ~strcmp('sint16',   type) & ...      
    ~strcmp('int16',    type) & ...      
    ~strcmp('sint32',   type) & ...      
    ~strcmp('int',      type) & ...      
    ~strcmp('int32',    type) & ...      
    ~strcmp('sfloat',   type) & ...      
    ~strcmp('float',    type) & ...      
    ~strcmp('single',   type) & ...      
    ~strcmp('dfloat',   type) & ...      
    ~strcmp('double',   type) & ...      
    ~strcmp('scomplex', type) & ...      
    ~strcmp('dcomplex', type) & ...      
    ~strcmp('complex',  type) ...
    ) 
    truthValue = 0;
    error('nilio_checkType:  oops... unrecognized data type');
end
truthValue = 1;
