% NILIO_WRITECOLLECTION writes dipimage objects to files
%
% USAGE: nilio_writecollection(image, type, filename)
%
%  possible types...
%     bin          <-> bin8, bin16, bin32
%     uint8
%     uint16
%     uint32       <-> uint
%     sint8        <-> int8
%     sint16       <-> int16
%     sint32       <-> int, int32
%     sfloat       <-> float, single
%     dfloat       <-> double
%     scomplex
%     dcomplex     <-> complex
%
% SEE ALSO:
%     nilio_readcollection
%
% $Author: jjlee $
% $Date: 2003/10/23 03:27:30 $
% $Revision: 1.2 $
% $Source: /cygdrive/c/local/dipimage-23jun2003/local/RCS/nilio_writecollection.m,v $


function nilio_writecollection(image, type, filename)

  % check for silly inputs
  if (strcmp('', filename)) error('oops... missing filename'); end
  if (~strcmp('bin', type) & ... 
      ~strcmp('bin8', type) & ...
      ~strcmp('bin16', type) & ...
      ~strcmp('bin32', type) & ...
      ~strcmp('uint8', type) & ...      
      ~strcmp('uint16', type) & ...      
      ~strcmp('uint32', type) & ...      
      ~strcmp('uint', type) & ...      
      ~strcmp('sint8', type) & ...      
      ~strcmp('int8', type) & ...      
      ~strcmp('sint16', type) & ...      
      ~strcmp('int16', type) & ...      
      ~strcmp('sint32', type) & ...      
      ~strcmp('int', type) & ...      
      ~strcmp('int32', type) & ...      
      ~strcmp('sfloat', type) & ...      
      ~strcmp('float', type) & ...      
      ~strcmp('single', type) & ...      
      ~strcmp('dfloat', type) & ...      
      ~strcmp('double', type) & ...      
      ~strcmp('scomplex', type) & ...      
      ~strcmp('dcomplex', type) & ...      
      ~strcmp('complex', type) ...
      ) error('oops... unrecognized data type'); end
  
  ByteOrder = 'native';

  fid = fopen(filename, 'w+', ByteOrder);
  fwrite(fid, double(image), type);
  fclose(fid);
  