%OSVDTIMES
%
%  USAGE:  [aTime] = osvdTimes(idx, metric)
%
%          idx is an integer index
%
%  SYNOPSIS:
%
%  SEE ALSO:  'Cell Arrays of Strings' or 'strings, cells arrays of' in Matlab help.
%
%  $Id$
%________________________________________________________________________
function [aTime] = osvdTimes(idx, metric)

cbfTimes = { '234' ...
          '140' ...
          '734' ...
          '296' ...
          '312' ...
          '31' ...
          '593' ...
          '250' ...
          '359' ...
          '328' ...
          '375' ...
          '937' ...
          '187' ...
          '234' ...
          '312' ...
          '515' ...
          '921' ...
          '500' ...
          '812' };
      
cbvTimes = { '93' ...
          '93' ...
          '109' ...
          '140' ...
          '484' ...
          '78' ...
          '203' ...
          '484' ...
          '328' ...
          '125' ...
          '703' ...
          '687' ...
          '265' ...
          '62' ...
          '468' ...
          '281' ...
          '187' ...
          '406' ...
          '515' };
      
mttTimes = { '203' ...
          '703' ...
          '984' ...
          '984' ...
          '828' ...
          '93' ...
          '453' ...
          '78' ...
          '968' ...
          '984' ...
          '171' ...
          '546' ...
          '625' ...
          '921' ...
          '328' ...
          '906' ...
          '843' ...
          '968' ...
          '937' };      
         
sizes = size(cbfTimes);
len   = sizes(2);

switch metric
    case 'cbf'
        if (idx < 1)
            aTime = cbfTimes;          
        elseif (idx > len)    
            aTime = cbfTimes(len);
            aTime = char(aTime);
        else
            aTime = cbfTimes(idx);
            aTime = char(aTime);
        end
    case 'cbv'
        if (idx < 1)
            aTime = cbvTimes;          
        elseif (idx > len)    
            aTime = cbvTimes(len);
            aTime = char(aTime);
        else
            aTime = cbvTimes(idx);
            aTime = char(aTime);
        end
    case 'mtt'
        if (idx < 1)
            aTime = mttTimes;          
        elseif (idx > len)    
            aTime = mttTimes(len);
            aTime = char(aTime);
        else
            aTime = mttTimes(idx);
            aTime = char(aTime);
        end
    otherwise
        error(['osvdTimes could not recognize ' metric]);
end
