%PEEKSCATTERROIS
%
%  SYNOPSIS:  peekScatterROIs(x, y, itsTitle)
%             peekScatterROIs(x, y, itsTitle, xlabel, ylabel)
%
%         x:           matlab array or dipimage object of abscissa data
%                      values as column vector
%         y:           matlab array or dipimage object of ordinate data
%                      values as column vector
%         itsTitle:    string
%         xlabel:      string
%         ylabel:      string
%
%  SEE ALSO:  gscatter, scatter, myscatter
%
% $Id$
%
function peekScatterROIs(x, y, itsTitle, xlabel, ylabel)

x = scrubNaNs(x);
y = scrubNaNs(y);
if (isa(x, 'dip_image')) x = double(x)'; end
if (isa(y, 'dip_image')) y = double(y)'; end

if size(y,1) ~= size(x,1), 
    error(['Oops...  len y -> ' num2str(size(y,1)) ' but len x -> ' num2str(size(x,1)) ...
           '; x and y must be the same length for use by scatter functions']); end
N      = size(y,1);
NPIDS  = 19;
NROIS  = 3;
NSIDES = 2;

switch (N)
    case NPIDS*NROIS*NSIDES
        group_byregion = { ...
            'grey'; 'grey'; 'basal ganglia'; 'basal ganglia'; 'white'; 'white';...
            'grey'; 'grey'; 'basal ganglia'; 'basal ganglia'; 'white'; 'white';...
            'grey'; 'grey'; 'basal ganglia'; 'basal ganglia'; 'white'; 'white';...
            'grey'; 'grey'; 'basal ganglia'; 'basal ganglia'; 'white'; 'white';...
            'grey'; 'grey'; 'basal ganglia'; 'basal ganglia'; 'white'; 'white';...
            'grey'; 'grey'; 'basal ganglia'; 'basal ganglia'; 'white'; 'white';...
            'grey'; 'grey'; 'basal ganglia'; 'basal ganglia'; 'white'; 'white';...
            'grey'; 'grey'; 'basal ganglia'; 'basal ganglia'; 'white'; 'white';...
            'grey'; 'grey'; 'basal ganglia'; 'basal ganglia'; 'white'; 'white';...
            'grey'; 'grey'; 'basal ganglia'; 'basal ganglia'; 'white'; 'white';...
            'grey'; 'grey'; 'basal ganglia'; 'basal ganglia'; 'white'; 'white';...
            'grey'; 'grey'; 'basal ganglia'; 'basal ganglia'; 'white'; 'white';...
            'grey'; 'grey'; 'basal ganglia'; 'basal ganglia'; 'white'; 'white';...
            'grey'; 'grey'; 'basal ganglia'; 'basal ganglia'; 'white'; 'white';...
            'grey'; 'grey'; 'basal ganglia'; 'basal ganglia'; 'white'; 'white';...
            'grey'; 'grey'; 'basal ganglia'; 'basal ganglia'; 'white'; 'white';...
            'grey'; 'grey'; 'basal ganglia'; 'basal ganglia'; 'white'; 'white';...
            'grey'; 'grey'; 'basal ganglia'; 'basal ganglia'; 'white'; 'white';...
            'grey'; 'grey'; 'basal ganglia'; 'basal ganglia'; 'white'; 'white'...
            };
        colors  = 'kkkkbbkkkkbbkkkkbbkkkkbbkkkkbbkkkkbbkkkkbbkkkkbbkkkkbbkkkkbbkkkkbbkkkkbbkkkkbbkkkkbbkkkkbbkkkkbbkkkkbbkkkkbbkkkkbb';
        symbols = 'ooddooooddooooddooooddooooddooooddooooddooooddooooddooooddooooddooooddooooddooooddooooddooooddooooddooooddooooddoo'; 
        sizes = [ ...
            8; 8; 8; 8; 8; 8; ...
            8; 8; 8; 8; 8; 8; ...
            8; 8; 8; 8; 8; 8; ...
            8; 8; 8; 8; 8; 8; ...
            8; 8; 8; 8; 8; 8; ...
            8; 8; 8; 8; 8; 8; ...
            8; 8; 8; 8; 8; 8; ...
            8; 8; 8; 8; 8; 8; ...
            8; 8; 8; 8; 8; 8; ...
            8; 8; 8; 8; 8; 8; ...
            8; 8; 8; 8; 8; 8; ...
            8; 8; 8; 8; 8; 8; ...
            8; 8; 8; 8; 8; 8; ...
            8; 8; 8; 8; 8; 8; ...
            8; 8; 8; 8; 8; 8; ...
            8; 8; 8; 8; 8; 8; ...
            8; 8; 8; 8; 8; 8; ...
            8; 8; 8; 8; 8; 8; ...
            8; 8; 8; 8; 8; 8 ];
    case NPIDS*NROIS
        NSIDES = 1;
        group_byregion = { ...
            'grey'; 'basal ganglia'; 'white';...
            'grey'; 'basal ganglia'; 'white';...
            'grey'; 'basal ganglia'; 'white';...
            'grey'; 'basal ganglia'; 'white';...
            'grey'; 'basal ganglia'; 'white';...
            'grey'; 'basal ganglia'; 'white';...
            'grey'; 'basal ganglia'; 'white';...
            'grey'; 'basal ganglia'; 'white';...
            'grey'; 'basal ganglia'; 'white';...
            'grey'; 'basal ganglia'; 'white';...
            'grey'; 'basal ganglia'; 'white';...
            'grey'; 'basal ganglia'; 'white';...
            'grey'; 'basal ganglia'; 'white';...
            'grey'; 'basal ganglia'; 'white';...
            'grey'; 'basal ganglia'; 'white';...
            'grey'; 'basal ganglia'; 'white';...
            'grey'; 'basal ganglia'; 'white';...
            'grey'; 'basal ganglia'; 'white';...
            'grey'; 'basal ganglia'; 'white'...
            };
        colors  = 'kbkkbkkbkkbkkbkkbkkbkkbkkbkkbkkbkkbkkbkkbkkbkkbkkbkkbkkbk';
        symbols = 'odoodoodoodoodoodoodoodoodoodoodoodoodoodoodoodoodoodoodo'; 
        sizes = [ ...
            8; 8; 8; 8; 8; 8; ...
            8; 8; 8; 8; 8; 8; ...
            8; 8; 8; 8; 8; 8; ...
            8; 8; 8; 8; 8; 8; ...
            8; 8; 8; 8; 8; 8; ...
            8; 8; 8; 8; 8; 8; ...
            8; 8; 8; 8; 8; 8; ...
            8; 8; 8; 8; 8; 8; ...
            8; 8; 8; 8; 8; 8; ...
            8; 8; 8; 8; 8; 8; ...
            8; 8; 8; 8; 8; 8; ...
            8; 8; 8; 8; 8; 8; ...
            8; 8; 8; 8; 8; 8; ...
            8; 8; 8; 8; 8; 8; ...
            8; 8; 8; 8; 8; 8; ...
            8; 8; 8; 8; 8; 8; ...
            8; 8; 8; 8; 8; 8; ...
            8; 8; 8; 8; 8; 8; ...
            8; 8; 8; 8; 8; 8 ];
    case NPIDS*NSIDES
        NROIS  = 1;
        group_byregion = { ...
            'contra'; 'ipsi';...
            'contra'; 'ipsi';...
            'contra'; 'ipsi';...
            'contra'; 'ipsi';...
            'contra'; 'ipsi';...
            'contra'; 'ipsi';...
            'contra'; 'ipsi';...
            'contra'; 'ipsi';...
            'contra'; 'ipsi';...
            'contra'; 'ipsi';...
            'contra'; 'ipsi';...
            'contra'; 'ipsi';...
            'contra'; 'ipsi';...
            'contra'; 'ipsi';...
            'contra'; 'ipsi';...
            'contra'; 'ipsi';...
            'contra'; 'ipsi';...
            'contra'; 'ipsi';...
            'contra'; 'ipsi'...
            };
        colors  = 'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk';
        symbols = 'cxcxcxcxcxcxcxcxcxcxcxcxcxcxcxcxcxcxcx'; 
        sizes = [ ...
            8; 8; 8; 8; 8; 8; 8; 8; 8; 8; 8; 8; 8; 8; 8; 8; 8; 8; 8; ...
            8; 8; 8; 8; 8; 8; 8; 8; 8; 8; 8; 8; 8; 8; 8; 8; 8; 8; 8 ];
    case NPIDS
        NROIS  = 1;
        NSIDES = 1;
        group_byregion = { ...
            'pt1';  'pt2';  'pt3';  'pt4';  'pt5';  'pt6';  'pt7';  'pt8';  'pt9'; 'pt10'; ...
            'pt11'; 'pt12'; 'pt13'; 'pt14'; 'pt15'; 'pt16'; 'pt17'; 'pt18'; 'pt19' };
        colors  = 'kkkkkkkkkkkkkkkkkkk';
        symbols = 'ooooooooooooooooooo'; 
        sizes = [ ...
            8; 8; 8; 8; 8; 8; 8; 8; 8; 8; 8; 8; 8; 8; 8; 8; 8; 8; 8];
    otherwise
        error(['unexpected number of abscissa and ordinate values -> ' num2str(N)]);
end
        
if nargin < 3,
    itsTitle = 'TITLE'; end
if nargin < 4,
    xlabel = 'X'; end
if nargin < 5,
    ylabel = 'Y'; end

if NROIS > 1, dolegend = 'on'; 
else          dolegend = 'off'; end

gscatter(x, y, group_byregion, colors, symbols, sizes, dolegend, xlabel, ylabel)
title(itsTitle, 'FontSize', 16, 'FontWeight', 'demi')
