% PERFUSIONPATH
%
% Usage:	pathString = perfusionPath(appendSep, appendFullfile)
%
%			append a separator to the filesystem path (optional)
%			append a partial path as generated by fullfile (optional)
%
% See also:  fullfile
%

function pathString = perfusionPath(appendSep, appendFullfile) ...

	if nargin ~= 2, appendFullfile = ''; end
	if nargin < 1,  appendSep = 0;       end
	
	if ispc
		prefix = 'P:'
	elseif isunix
		prefix = '/mnt/hgfs';
	else
		error(['perfusionPath could not recognize computer -> ' computer]);
	end
	if appendSep, sep = filesep;
		else sep = ''; end
		
	pathString = fullfile(prefix, 'perfusion', 'vc', appendFullfile, sep);
