%READASCII integrates into the dipimage GUI & reads images from 
%          single-column ascii floats as used by Larry Bretthorst
%
% SYNOPSIS:
%  image_out = readAscii(varargin)
%
% SEE ALSO:
%  readcollection
%  nilio_readAscii
%
% NOTES:
%  Reads ASCII data according to function nilio_readAscii.
%  Resulting images are in radiologic convention when viewed with DIPimage.
%  Derived from READIM and readcollection.   
%
% $Author: jjlee $
% $Date$
% $Revision$
% $Source$
% ________________________________________________________________
% (C) Copyright 2005                    Neuroimaging Laboratory
%     All rights reserved               Mallinckrodt Institute of 
%                                       Radiology
%                                       4525 Scott Ave, Box 8225
%                                       St. Louis, MO  63110
%
% John Lee, June 2003: Implemented basic functions for reading MR files
% generated by Siemens Magnetom Vision systems (SPI native format)
% Oct 2004: Implemented support for Avi Snyder's 4dfp format

function image_out = readAscii(varargin)

  d = struct('menu','File I/O',...
	     'display','Read 4D data',...
	     'inparams',struct(...
                   'name',       {'filename',                 'dim1',            'dim2',            'dim3',            'dim4'},...
			       'description',{'Name of the file to open', 'Size of 1st Dim', 'Size of 2nd Dim', 'Size of 3rd Dim', 'Size of 4th Dim'},...
			       'type',       {'infile',  'array', 'array', 'array', 'array'},...
			       'dim_check',  {0,         0,       0,       0,       0},...
			       'range_check',{'*.*',     'N+',    'N+',    'N+',    'N+'},...
			       'required',   {1,         0,       0,       0,       0},...
			       'default',    {'',        256,     256,     1,      1} ),...
	     'outparams',struct(...
                'name',{'image_out'},...
				'description',{'Output image'},...
				'type',{'image'}...
				)...
	     );
  if nargin == 1
    s = varargin{1};
    if ischar(s) & strcmp(s,'DIP_GetParamList')
      image_out = d;
      return
    end
  end
  
  try
    [filename, dim1, dim2, dim3, dim4] = getparams(d,varargin{:});
  catch
    if ~isempty(paramerror)
      error(paramerror)
    else
      error(firsterr)
    end
  end  
  
  try
    image_out = nilio_readAscii(filename, dim1, dim2, dim3, dim4);
  catch
    error('sorry...  nilio_readAscii failed')
  end