function startupTests_R2013a(varargin)
%% STARTUPTESTS_R2013A ... 
%  Usage:  startupTests([list-of-tests]) 
%                        ^ packageName.TestName, or cell-array of, or 'all'
%
%% Version $Revision: 2650 $ was created $Date: 2013-09-21 17:59:39 -0500 (Sat, 21 Sep 2013) $ by $Author: jjlee $,  
%% last modified $LastChangedDate: 2013-09-21 17:59:39 -0500 (Sat, 21 Sep 2013) $ and checked into svn repository $URL: file:///Users/jjlee/Library/SVNRepository_2012sep1/mpackages/mfiles/trunk/startupTests_R2013a.m $ 
%% Developed on Matlab 7.12.0.635 (R2011a) 
%% $Id$ 

BASE_LIST = { ...
    'mlio_xunit.Test_IOInterface' ...
    'mlio_xunit.Test_AbstractIO' ...
    'mlio_xunit.Test_TextIO' ...
    'mlsystem_xunit.Test_SafeDir' ...
    'mlsystem_xunit.Test_DirToolComponent' ...
    'mlfourd_xunit.Test_NIfTI' ...
    'mlfourd_xunit.Test_BlurredNIfTI' ...
    'mlfourd_xunit.Test_NiiBrowser' ...
    'mlfourd_xunit.Test_ImagingArrayList' ...
    'mlfourd_xunit.Test_ImagingComponent' ...
    'mlfourd_xunit.Test_ImagingSeries' ...
    'mlfourd_xunit.Test_ImagingComposite' ...
    'mlfourd_xunit.Test_ImagingContext' ...
    'mlcaster_xunit.Test_CasterContext' ...
    'mlcaster_xunit.Test_CasterStrategy' ...
    'mlchoosers_xunit.Test_ImageFilters' ...
    'mlchoosers_xunit.Test_FilenameFilters' ...
    'mlchoosers_xunit.Test_ImagingChoosers' ...
    'mlsurfer_xunit.Test_SurferDicomConverter' ...
    'mlpet_xunit.Test_PETAlignmentDirector' ...
    'mlmr_xunit.Test_MRAlignmentDirector' ...
    'mlfsl_xunit.Test_BrainExtractionVisitor' ...
    'mlfsl_xunit.Test_MorphingDirector' ...
    'mlsurfer_xunit.Test_VolumeRoiCorticalThicknessBuilder' ...
    'mlsurfer_xunit.Test_Parcellations' ...
    'mlsurfer_xunit.Test_PETSegstatsBuilder' ...
    'mlsurfer_xunit.Test_PerfusionSegstatsBuilder' ...
    'mlsurfer_xunit.Test_ADCSegstatsBuilder' ...
    };
EXTRA_LIST = { ... 
    'mlfourd_xunit.Test_MRIConverter' ...
    'mlfourd_xunit.Test_PETConverter' ...  
    'mlfsl_xunit.Test_FslBuilder' ...
    'mlfsl_xunit.Test_FlirtBuilder' ...
    'mlfsl_xunit.Test_FnirtBuilder' ...
    'mlfsl_xunit.Test_FastBuilder' ...
    'mlfsl_xunit.Test_BetBuilder' ...
    'mlpipeline.Test_CorticalThickness' ...  
    'mlmr_xunit.Test_MRIBuilder' ...
    'mlpet_xunit.Test_PETBuilder' ...
    'mlpipeline_xunit.Test_mfiles' ...
    };  

p = inputParser;
addOptional(p, 'listOfTests', BASE_LIST, @(x) (ischar(x) || iscell(x)) && ~isempty(x));
parse(p, varargin{:});
listOfTests = p.Results.listOfTests;

if (ischar(listOfTests))
    listOfTests = ensureCell(listOfTests); end
for t = 1:length(listOfTests)
	try
        if (lstrfind(listOfTests{t}, { 'all', 'base_list' 'BASE_LIST' }))            
            startupTests_R2013a(BASE_LIST); end
        if (lstrfind(listOfTests{t}, { 'all' 'fsl_list' 'FSL_LIST' }))
            startupTests_R2013a(FSL_LIST); end
    	runtests(listOfTests{t}, '-verbose');
	catch ME
		handwarning(ME);
	end
end







% Created with NEWFCN.m by Frank Gonzalez-Morphy (frank.gonzalez-morphy@mathworks.de) 
% ===== EOF ====== [/Users/jjlee/Local/src/mpackages/mfiles/startupTests_R2013a.m] ======  
