function S = test_checkfield(varargin)

listfields = { ...
    'Method',...
    'Number' };

testvalid = { ...
    @ischar, ...
    @(i) isnumeric(i) & i>0 };

acceptablevalues = {
    {'method1', 'method2', 'all'}, ...
    {1,2,3,4}, ...
    {} };

default = struct( ...
    'method','all', ...
    'number',1);

disp(varargin)
disp(class(varargin))
disp(size(varargin))

S = checkfield(varargin,listfields,testvalid,acceptablevalues,default);
